{VER
ver:2
}
{LIB
act:A
acc:pacbio
ori:U
mea:0.000
std:0.000
src:
.
nft:20
fea:
forceBOGunitigger=0
isNotRandom=0
doNotTrustHomopolymerRuns=0
doTrim_initialNone=0
doTrim_initialMerBased=0
doTrim_initialFlowBased=0
doTrim_initialQualityBased=1
doRemoveDuplicateReads=0
doTrim_finalLargestCovered=0
doTrim_finalEvidenceBased=1
doTrim_finalBestEdge=0
doRemoveSpurReads=1
doRemoveChimericReads=1
doCheckForSubReads=0
doConsensusCorrection=0
forceShortReadFormat=0
constantInsertSize=0
fastqQualityValues=sanger
fastqOrientation=innie
fastqReads=/lustre/hpcprod/mkinsella/arab_test/corrected.fastq
.
}
{VER
ver:1
}
